### ISSUE TITLE
Add Auto-Cancelling Redundant Builds Feature to CI/CD Workflow

### ISSUE THREAD

**Issue by sbolel** [CMS-Enterprise/sbom-harbor-ui#74]
**Description**

This issue is to request the implementation of auto-cancelling redundant builds in our CI/CD workflow.

- What did you expect to happen?
  With frequent pushes or pull requests, I expect the CI/CD system to optimize resources by only running the latest workflow, and cancelling any redundant, older workflows that are no longer relevant.

- What happened instead?
  Currently, every push or pull request triggers a new workflow run, even if older runs are still in progress or in the queue. This can consume unnecessary resources and lengthen the time it takes to get feedback on a change.

- What would you like to see changed?
  I would like to see the implementation of auto-cancelling redundant builds. This feature would automatically cancel any previous runs of the same workflow that are either in progress or in the queue whenever a new run starts.

The benefit of this feature is that it will help conserve our CI/CD resources, potentially speeding up feedback on changes and making our entire development process more efficient.

**Procedure**

To implement this feature, we can use a GitHub Action such as `technote-space/auto-cancel-action`. This action would be added as a new step at the beginning of our workflow. The action will need to be configured with the `cancel-in-progress` parameter set to `true` to cancel both in-progress and queued workflows. The `GITHUB_TOKEN` will be used to provide the necessary permissions for the action to cancel workflows. 

Here's a high-level example of the changes that would need to be made to the workflow:

```yml
jobs:
  test_build_release:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Cancel Previous Runs
        uses: technote-space/auto-cancel-action@v2
        with:
          cancel-in-progress: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: CHECKOUT
        uses: actions/checkout@v3

      # ...rest of your steps
```

After implementing these changes, we should thoroughly test our workflow to ensure everything is working as expected.
